class AppList {
  static final List<Map<String, String>> relationshipGoals = [
    {
      'key': 'dating',
      'title': 'Dating 👩‍❤️‍👨',
      'subtitle': 'Seeking love and meaningful connections? Choose dating for genuine relationships.',
    },
    {
      'key': 'friendship',
      'title': 'Friendship 🙌',
      'subtitle': 'Expand your social circle and make new friends. Opt for friendship today.',
    },
    {
      'key': 'casual',
      'title': 'Casual 😄',
      'subtitle': 'Looking for fun and relaxed encounters? Select casual for carefree connections.',
    },
    {
      'key': 'serious',
      'title': 'Serious Relationship 💍',
      'subtitle': 'Ready for commitment and a lasting partnership? Pick serious relationship.',
    },
    {
      'key': 'open',
      'title': 'Open to Options 🌟',
      'subtitle': 'Explore various connections and keep your options open with this choice.',
    },
    {
      'key': 'networking',
      'title': 'Networking 🤝',
      'subtitle': 'Connect professionally and expand your network. Choose networking now.',
    },
    {
      'key': 'exploration',
      'title': 'Exploration 🌍',
      'subtitle': 'Embark on a journey of discovery. Select exploration for new experiences.',
    },
  ];

  static final List<String> interests = [
    'Travel ✈️',
    'Cooking 🍳',
    'Hiking 🏞️',
    'Yoga 🧘',
    'Gaming 🎮',
    'Movies 🎥',
    'Photography 📷',
    'Music 🎵',
    'Pets 🐱',
    'Painting 🎨',
    'Art 🎨',
    'Fitness 💪',
    'Reading 📖',
    'Dancing 💃',
    'Sports 🏀',
    'Board Games 🎲',
    'Technology 📱',
    'Fashion 👗',
    'Motorcycling 🏍️',
    'Science 🔬',
    'History 📜',
    'Nature 🌿',
    'Adventure 🌄',
    'Gardening 🌻',
    'Foodie 🍽️',
    'Writing ✍️',
    'Poetry 📝',
    'Astronomy 🔭',
    'Sustainable Living 🌱',
    'Film Production 🎬',
    'Meditation 🧘‍♂️',
    'Comedy 😄',
    'Volunteering 🤝',
    'DIY Projects 🛠️',
    'Art History 🏛️',
    'Philosophy 🧠',
    'Snowboarding 🏂',
    'Wine Tasting 🍷',
    'Collectibles 🎩',
    'Sailing ⛵',
    'Karaoke 🎤',
    'Surfing 🏄',
    'Scuba Diving 🌊',
    'Skydiving 🪂',
    'Pottery 🏺',
    'Wildlife Conservation 🦁',
    'Ghost Hunting 👻',
    'Geocaching 🌐',
    'Stand-up Comedy 🎙️',
    'Motor Racing 🏁',
    'Paranormal Investigation 🕵️‍♂️',
  ];

  static final List<String> musicPref = [
    "Pop 🎵",
    "Rock 🎸",
    "R&B 🎶",
    "Country 🤠",
    "Jazz 🎷",
    "Hip-Hop 🎤",
    "Classical 🎻",
    "Electronic 🎧",
    "Indie 🎶",
    "Reggae 🌴",
    "Blues 🎺",
    "Metal 🤘",
    "Latin 💃",
    "K-Pop 🇰🇷",
    "EDM 🕺",
    "Funk 🎺",
    "World 🌍",
    "Opera 🎭",
    "Soul 🎵",
    "Rap 🎤",
    "Disco 💃",
    "Ambient 🌌",
    "Ska 🏁",
    "Gospel 🙌",
    "House 🏠",
    "New Age 🌅",
    "Trance 🚀",
    "Techno 🎶",
    "Salsa 💃",
    "Flamenco 💃",
    "Swing 🎶",
    "Chiptune 🎮",
    "Barbershop 🎤",
    "Chamber 🎻",
    "Choir 🎶",
    "Acoustic 🎸",
    "Synth-Pop 🎹",
    "Grunge 🎸",
    "Punk 🤟",
    "Alternative 🎶",
    "Industrial 🏭",
    "World Fusion 🌍",
    "Trip-Hop 🚶‍♂️🎶",
    "Progressive 🎶",
    "Experimental 🎵",
    "J-Pop 🎌",
  ];

  static final List<String> moviePref = [
    "Action 🎬",
    "Comedy 😂",
    "Thriller 🌡️",
    "Drama 🎭",
    "Sci-Fi 🚀",
    "Romance 💖",
    "Plays 🎬",
    "Animated 🎈",
    "Spy 🕵️‍♂️",
    "Historical 🏰",
    "War ⚔️",
    "Horror 🧟‍♂️",
    "Crime 🕵️‍♂️",
    "Mystery 🔍",
    "Western 🤠",
    "Travel ✈️",
    "Business 📊",
    "True Crime 🕵️‍♂️",
    "Film Noir 🌃",
    "Documentary 📽️",
    "Cyberpunk 🤖",
    "Fantasy 🌟",
    "Space Opera 🚀🌌",
    "Adventure 🌄",
    "Epic 🎥",
    "Romance 💕",
    "Horror 🦇",
    "Animated 🎈",
    "K-Drama 🇰🇷🎭",
    "Foreign Films 🌍🎬",
    "Silent Films 🎞️",
    "Disaster 🌪️",
    "Mockumentary 📹",
    "Cult Classics 🎬👽",
    "Buddy Cop 👮‍♂️👮‍♂️",
    "Political 🏛️",
    "Satire 😄",
    "Noir 🌆",
    "Cyberpunk 🤖",
    "Bollywood 🎥",
    "Nollywood 🇳🇬📽️",
  ];

  static final List<String> bookPref = [
    "Fiction 📚",
    "Non-Fiction 📖",
    "Sci-Fi 🚀",
    "Fantasy 🌌",
    "Historical Fiction 🏰",
    "Biography 📜",
    "Self-Help 📈",
    "Poetry 📝",
    "Essays 📝",
    "Young Adult 📖",
    "Classic Literature 📜",
    "Mystery/Thriller 🕵️‍♂️",
    "Paranormal 👻",
    "Science 🔬",
    "Romance 💖",
    "Comics 📚🎨",
    "Plays 🎬",
    "Graphic Novels 📖🎨",
    "Travelogues 🌍🗺️",
    "True Crime 🕵️‍♂️",
    "Autobiography 📖📜",
    "Religious Texts 📜🙏",
    "Anthologies 📚📖",
    "Memoir 📔",
    "Art & Photography 🎨📷",
    "Dystopian 🌆",
    "Science Fiction Fantasy 🚀🌌",
    "Satire 😂",
    "Cookbooks 🍳",
    "Alternate History 🌐",
    "Short Stories 📖📜",
    "Children's Books 📚👶",
    "Philosophy 🧠",
    "Humor 😄",
    "Business 📊",
    "Drama 🎭",
  ];

  static final List<String> travelPref = [
    "Adventure Travel 🏞️",
    "City Breaks 🌆",
    "Cultural Exploration 🏛️",
    "Glamping ⛺",
    "Beach Vacations 🏖️",
    "Nature Escapes 🌿",
    "Relaxing Getaways 🏨",
    "Road Trips 🚗",
    "Cruise Vacations 🚢",
    "Staycations 🏡",
    "Food Tourism 🍔",
    "Backpacking 🎒",
    "Wine Tours 🍷",
    "Wildlife Safaris 🦁",
    "Skiing/Snowboarding ⛷️",
    "Eco-Tourism 🌿",
    "Music Festivals 🎵",
    "Culinary Tours 🍴",
    "Yoga Retreats 🧘‍♀️",
    "Group Tours 🚌",
    "Island Hopping 🏝️",
    "Train Journeys 🚆",
    "Remote Destinations 🏞️",
    "Volunteering Abroad 🌍",
    "Mountain Retreats 🏔️",
    "Desert Adventures 🌵",
    "Solo Travel 🚶‍♀️",
    "Spa Getaways 💆‍♀️",
  ];

  static final List<String> zodiac = [
    "Aries",
    "Taurus",
    "Gemini",
    "Cancer",
    "Leo",
    "Virgo",
    "Libra",
    "Scorpio",
    "Sagittarius",
    "Capricorn",
    "Aquarius",
    "Pisces",
    "None",
  ];

  static final List<String> pets = [
    "Dog",
    "Cat",
    "Fish",
    "Bird",
    "Rabbit",
    "Hamster",
    "Reptile",
    "Exotic Pet",
    "Other",
  ];

  static final List<String> drinkingHabits = [
    "Social Drinker",
    "Occasional Drinker",
    "Non-Drinker",
    "Wine Enthusiast",
    "Craft Beer Lover",
    "Cocktail Connoisseur",
  ];
  static final List<String> workout = [
    "Daily",
    "Weekly",
    "Occasional",
    "Never",
  ];
  static final List<String> smokingHabits = [
    "Smoker",
    "Non-Smoker",
    "Occasional Smoker",
    "Vape Enthusiast",
    "Quitter",
  ];
  static final List<String> education = [
    "High School",
    "Bachelors",
    "Masters",
    "PhD",
    "Trade School",
    "Other",
  ];
  static final List<String> familyPlans = [
    "Want Kids",
    "Don't Want Kids",
    "Not Sure Yet",
  ];
  static final List<String> dietPref = [
    "Vegetarian",
    "Vegan",
    "Omnivore",
    "Pescatarian",
    "Halal",
    "Kosher",
    "Gluten-Free",
    "Dairy-Free",
    "Plant-Based",
    "Keto",
    "Raw Food",
    "Other",
  ];
  static final List<String> personalityTypes = [
    "INTJ",
    "INTP",
    "ENTJ",
    "ENTP",
    "INFJ",
    "INFP",
    "ENFJ",
    "ENFP",
    "ISTJ",
    "ISFJ",
    "ESTJ",
    "ESFJ",
    "ISTP",
    "ISFP",
    "ESTP",
    "ESFP",
  ];
  static final List<String> loveStyle = [
    "Hopeless Romantic",
    "Adventure Seeker",
    "Best Friend",
    "Independent Spirit",
    "Caregiver",
    "Classic Lover",
    "Analytical Lover",
  ];
  static final List<String> communicationStyle = [
    "Chatty Cathy",
    "Listener",
    "Joker",
    "Deep Thinker",
    "Sarcastic Wit",
    "Easygoing",
    "Straight Shooter",
    "Storyteller",
  ];
  static final List<String> bloodType = [
    "A",
    "B",
    "AB",
    "O",
    "Other",
  ];

  static final List<String> socialMediaPresence = [
    "Active on All",
    "Active on Some",
    "Minimal Social Media Presence",
    "Social Media Influencer",
  ];

  static final List<String> sleepingHabits = [
    "Early Bird",
    "Night Owl",
    "Regular Sleeper",
    "Insomniac",
  ];
  static final List<String> hobbies = [
    "Craft & Hobbies 🎨🛠️",
    "Art Galleries 🎨",
    "Historical Sites 🏰",
  ];
  static final List<String> languages = [
    "English 🇺🇸",
    "Chinese 🇨🇳",
    "Hindi 🇮🇳",
    "Arabic 🇸🇦",
    "Bengali 🇧🇩",
    "Spanish 🇪🇸",
    "Portuguese 🇵🇹",
    "Russian 🇷🇺",
    "Japanese 🇯🇵",
    "French 🇫🇷",
    "Punjabi 🇮🇳",
    "German 🇩🇪",
    "Malay 🇲🇾",
    "Telugu 🇮🇳",
    "Urdu 🇵🇰",
    "Turkish 🇹🇷",
    "Marathi 🇮🇳",
    "Tamil 🇮🇳",
    "Korean 🇰🇷",
    "Vietnamese 🇻🇳",
    "Italian 🇮🇹",
    "Thai 🇹🇭",
    "Filipino (Tagalog) 🇵🇭",
    "Swahili 🇰🇪",
    "Dutch 🇳🇱",
    "Polish 🇵🇱",
    "Ukrainian 🇺🇦",
    "Romanian 🇷🇴",
    "Greek 🇬🇷",
    "Nepali 🇳🇵",
    "Hungarian 🇭🇺",
    "Czech 🇨🇿",
    "Danish 🇩🇰",
    "Hebrew 🇮🇱",
    "Swedish 🇸🇪",
    "Finnish 🇫🇮",
    "Norwegian 🇳🇴",
    "Slovak 🇸🇰",
    "Bulgarian 🇧🇬",
    "Other",
  ];
  static final List<String> religion = [
    "Christianity",
    "Islam",
    "Hinduism",
    "Buddhism",
    "Sikhism",
    "Judaism",
    "Bahá'í",
    "Jainism",
    "Chinese Traditional Religion",
    "Shinto",
    "Cao Dai",
    "Secular/Atheist/Agnostic",
    "Diasporic Religions",
    "Spiritism",
    "Other",
  ];
}
